### ISSUE TITLE
2.17.2 can fail if no files are found in 2.17.1

### ISSUE THREAD

**Issue by memelet** [awailly/cis-ubuntu-ansible#100]
```
TASK: [cis | 2.17.1 Set Sticky Bit on All World-Writable Directories (preparation) (Scored)] ***
skipping: [x.x.x.x]

TASK: [cis | 2.17.2 Set Sticky Bit on All World-Writable Directories (Scored)] ***
fatal: [x.x.x.x] => with_items expects a list or a set
```

But I don't see why 2.17.1 was skipped.  I certainly had no skip-tags specified.

**Comment by memelet** [comment]
I fully perplexed as to what could cause this to be skipped. I am running with no tag options at all. Could the always_run be having some strange effect?

```
  - name: 2.17.1 Set Sticky Bit on All World-Writable Directories (preparation) (Scored)
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 -print 2>/dev/null
    failed_when: False
    changed_when: False
    always_run: True
    register: sticky_bit_dirs
    tags:
      - section2
      - section2.17
      - section2.17.1
```
