### ISSUE TITLE
Skipping via tags on role yields lots of errors

### ISSUE THREAD

**Issue by memelet** [awailly/cis-ubuntu-ansible#135]
This is related #101, #102, #108 I think.

When I run 
```
  roles:
    - role: cis
      when: a_var_that_false|bool == false
```

I get errors for all the places where there is no default for an array, eg
```
TASK [cis : 8.2.4.2 Create and Set Permissions on rsyslog Log Files (Scored)] **
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

The PR that was ultimately applied I think only works for check mode but not when tasks are skipped like above for via --skip-tags. 

So I think the PR https://github.com/awailly/cis-ubuntu-ansible/pull/102 is still required.

We have been running with a branch that has had this applied for a long time. Just today I tried to using master and get gobs and gobs of errors.

**Comment by memelet** [comment]
Hmm, I think I misunderstood what happening. I still get the above errors even with mods like
```
- name: 8.2.4.2 Create and Set Permissions on rsyslog Log Files (Scored)
    shell: 'mkdir -p -- "$(dirname -- {{ item }})"; touch -- {{ item }}' 
    with_items: "{{result.stdout_lines | default([])}}"
    changed_when: False
    register: rsyslog_files_created
    tags:
      - section8
      - section8.2
      - section8.2.4
```
(note the `| default([])` in the with_items)

So maybe it's even worse now with 2.1.2.0. Before the default was enough, now default is not strong enough to overcome `result` not being set by the skipped task.
