### ISSUE TITLE
Role fails to run if skipped

### ISSUE THREAD

**Issue by memelet** [awailly/cis-ubuntu-ansible#89]
When the role is skipped, eg

```
  - role: cis
    when: some_variable_that_is_false
```

A 13.18 fails with

```
TASK: [cis | 13.18 Check for Presence of User .netrc Files (stat) (Scored)] ***
fatal: [10.0.139.165] => with_items expects a list or a set
fatal: [10.0.136.68] => with_items expects a list or a set
fatal: [10.0.137.117] => with_items expects a list or a set
```

This may or not be problem with ansible 2.0, but it is with 1.9.x. 

To handle this case the two 13.8 with_item values need to be changed to

```
    with_items: '{{ home_users.stdout_lines | default([]) }}'
    ...
    with_items: '{{ netrc_files.results | default([]) }}'
```

Why ever skip cis? When adding new nodes a cluster (eg, a new mesos-slave node) I will run the entire cluster playbook. The new node gets created and provisioned, but all the other nodes run too. Of course with good playbooks that's just a bunch of 'oks'. 

But with some type of nodes, for some of the cis tasks that check files or permissions, there are so many files to check that the playbook can take hours to complete. The mesos-slave for example, is runnign lots of docker containers and other mesos containers and will have a gazzilion data files. For these nodes, I set a value in `/etc/ansible/facts.d/cis_ubuntu.fact` indicating that cis has already run and not to do it again. 

PR on the way.

**Comment by awailly** [comment]
Good catch. Can you describe how you skipped the role? I wonder why only 13.18 is impacted by this issue. It looks like all defaults should be set this way.

What are the values of `home_users` and `netrc` when you skip the role? You can display this with a debug clause.

**Comment by memelet** [comment]
I don't know why it was just those two from 13.18, but no others had a problem. Ansible is not very consistent, or I should say intuitive, in how it deals with looping. In this case, I think the with_items is used as a generator and the tag filtering is applied for each generated task. So even if filtered there needs to be valid for the with_items.

In the case of 13.18 the variables are simply undefined.

This is the play I am now using for CIS:

```
- name: base | configure security - part b
  hosts: "{{hosts}}"
  become: yes
  tags: [base, base-security, cis]

  # https://github.com/awailly/cis-ubuntu-ansible

  vars:
    cis_set_configured: 
      configured: true

  pre_tasks:
    - setup: filter=ansible_local

    - set_fact:
        cis_configured: "{{ ansible_local.cis_ubuntu.configured if (ansible_local is defined and ansible_local.cis_ubuntu is defined and ansible_local.cis_ubuntu.configured is defined) else false }}" 

  roles:
    - role: cis
      root_password: "{{ cis_root_password }}"
      root_password_grub: "{{ cis_root_password_grub }}"
      apt_upgrade: false
      use_aide: false
      when: cis_configured|bool == false or (cis_force | default(false)) == true

  post_tasks:
    - file:
        state: directory
        path: /etc/ansible/facts.d/
        recurse: yes
        mode: 0755

    - copy:
        content: '{{cis_set_configured | to_nice_json }}'
        dest: /etc/ansible/facts.d/cis_ubuntu.fact
        mode: 0644
```
